/**
 * Single analytics taxonomy shared by the server sink and the browser client.
 *
 * Adding an event here is the only step required to make it available on both
 * sides. No provider (GA4, PostHog, Plausible) is referenced anywhere: the
 * browser client emits a DOM event and the server sink records to an opt-in
 * store, so a provider integration stays a drop-in change.
 */
export const ANALYTICS_EVENTS = [
  "page_view",
  "landing_viewed",
  "product_menu_opened",
  "navigation_product_menu_opened",
  "navigation_product_category_clicked",
  "navigation_product_clicked",
  "navigation_free_tool_clicked",
  "navigation_link_in_bio_clicked",
  "navigation_cta_clicked",
  "product_viewed",
  "product_cta_clicked",
  "product_related_clicked",
  "product_cross_sell_clicked",
  "pricing_viewed",
  "signup_clicked",
  "login_clicked",
  "free_tool_started",
  "free_tool_completed",
  "link_submitted",
  "link_analyzed",
  "link_cleaned",
  "link_copied",
  "link_opened",
  "qr_generated",
  "qr_downloaded",
  "utm_generated",
  "url_check_requested",
  "url_check_completed",
  "smart_page_created",
  "smart_page_updated",
  "smart_page_published",
  "form_created",
  "form_block_added",
  "form_published",
  "smart_page_view",
  "smart_block_created",
  "smart_block_view",
  "smart_block_clicked",
  "whatsapp_link_created",
  "whatsapp_link_updated",
  "whatsapp_link_archived",
  "whatsapp_link_view",
  "whatsapp_link_click",
  "whatsapp_redirect",
  "whatsapp_link_copied",
  "whatsapp_qr_created",
  "whatsapp_template_used",
  "whatsapp_optimization_applied",
  "whatsapp_cta_created",
  "whatsapp_campaign_created",
  "dashboard_viewed",
  "quick_action_clicked",
  "module_opened",
  "create_action_started",
  "create_action_completed",
  "anonymous_usage_consumed",
  "signup_prompt_shown",
  "signup_started",
  "signup_completed",
  "onboarding_started",
  "onboarding_completed",
  "link_created",
  "smart_card_created",
  "qr_created",
  "campaign_created",
  "first_page_view",
  "first_click",
  "upgrade_clicked",
  "upgrade_viewed",
  "premium_feature_clicked",
  "trial_started",
  "trial_feature_used",
  "trial_7_days_remaining",
  "trial_3_days_remaining",
  "trial_expired",
  "trial_feature_used",
  "trial_7_days_remaining",
  "trial_3_days_remaining",
  "trial_expired",
  "goal_created",
  "goal_paused",
  "goal_archived",
  "goal_activated",
  "goal_viewed",
  "analytics_viewed",
  "analytics_period_changed",
  "analytics_filter_applied",
  "analytics_goal_clicked",
  "analytics_asset_opened",
  "journey_viewed",
  "journey_filter_changed",
  "journey_path_opened",
  "journey_campaign_opened",
  "audience_viewed",
  "contact_opened",
  "contact_tag_added",
  "contact_note_created",
  "segment_created",
  "segment_opened",
  "audience_filter_applied",
  "checkout_started",
  "subscription_started",
  "premium_subscription_started",
] as const;

export type AnalyticsEventName = (typeof ANALYTICS_EVENTS)[number];

// Operation results are recorded by their API handlers, never twice via the browser.
export const CLIENT_ANALYTICS_EVENTS = [
  "page_view",
  "landing_viewed",
  "product_menu_opened",
  "navigation_product_menu_opened",
  "navigation_product_category_clicked",
  "navigation_product_clicked",
  "navigation_free_tool_clicked",
  "navigation_link_in_bio_clicked",
  "navigation_cta_clicked",
  "product_viewed",
  "product_cta_clicked",
  "product_related_clicked",
  "product_cross_sell_clicked",
  "pricing_viewed",
  "signup_clicked",
  "login_clicked",
  "free_tool_started",
  "free_tool_completed",
  "link_submitted",
  "link_cleaned",
  "link_copied",
  "link_opened",
  "qr_downloaded",
  "url_check_requested",
  "whatsapp_link_copied",
  "dashboard_viewed",
  "quick_action_clicked",
  "module_opened",
  "create_action_started",
  "signup_prompt_shown",
  "signup_started",
  "signup_completed",
  "upgrade_clicked",
  "upgrade_viewed",
  "premium_feature_clicked",
  "trial_started",
  "analytics_viewed",
  "analytics_period_changed",
  "analytics_filter_applied",
  "analytics_goal_clicked",
  "analytics_asset_opened",
  "journey_viewed",
  "journey_filter_changed",
  "journey_path_opened",
  "journey_campaign_opened",
  "audience_viewed",
  "contact_opened",
  "contact_tag_added",
  "contact_note_created",
  "segment_created",
  "segment_opened",
  "audience_filter_applied",
] as const satisfies ReadonlyArray<AnalyticsEventName>;

export const ANALYTICS_PATHS = [
  "/",
  "/limpar-link",
  "/gerar-utm",
  "/gerar-qrcode",
  "/encurtar",
  "/link-health",
  "/analisar-link",
  "/produtos",
  "/precos",
  "/recursos",
  "/sobre",
  "/blog",
  "/ajuda",
  "/privacidade",
  "/termos",
  "/cookies",
  "/conta",
  "/untrack/short-links",
  "/untrack/whatsapp",
  "/untrack/campaigns",
  "/untrack/analytics",
  "/untrack/analytics/journey",
  "/untrack/audience",
  "/untrack/audience/segments",
  "/untrack/audience/forms",
  "/untrack/utm",
  "/untrack/qr",
  "/untrack/smart-pages",
  "/untrack/link-health",
  "/untrack/usage",
  "/upgrade",
  "/teste-premium",
  "/settings/plan",
  "/onboarding",
  "/entrar",
  "/cadastro",
] as const;

export function isAnalyticsPath(value: string): boolean {
  return (
    (ANALYTICS_PATHS as readonly string[]).includes(value) ||
    /^\/produtos\/[a-z0-9-]+$/.test(value)
  );
}

/** DOM event carrying `{ event }`, dispatched by the browser analytics client. */
export const ANALYTICS_BROWSER_EVENT = "arrume-meu-link:analytics";

export function isAnalyticsEventName(
  value: string,
): value is AnalyticsEventName {
  return (ANALYTICS_EVENTS as readonly string[]).includes(value);
}
